
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
