name: Build, Test and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync go.mod and go.sum
        run: go mod tidy

      - name: Run unit tests
        run: |
          echo "Ejecutando pruebas unitarias..."
          go test ./... -v -run ^TestStudentController$ ./controllers/student_controller_test.go
          go test ./... -v -run ^TestStudentService$ ./services/student_service_test.go

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hlopez:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/hlopez:latest'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Push image to Docker Hub
        if: success()
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/hlopez:latest

      - name: Run integration tests with Docker Compose
        run: |
          echo "Levantando contenedores..."
          docker compose up -d
          sleep 10  # espera a que inicie todo correctamente
          echo "Ejecutando pruebas de integración..."
          go test ./... -v -run ^TestStudentController$ ./controllers/student_controller_integration_test.go
          go test ./... -v -run ^TestStudentService$ ./services/student_service_integration_test.go
          docker compose down
