name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Instalar dependencias
        run: go mod tidy

      - name: Ejecutar pruebas unitarias
        run: |
          echo "Ejecutando pruebas unitarias..."
          
          go test ./... -v -run ^TestStudentController$ ./integration_tests/student_controller_test.go

      - name: Construir imagen Docker
        run: docker build -t go-mongo-app .

      - name: Levantar contenedores para pruebas de integración
        run: docker compose up -d

      - name: Esperar MongoDB
        run: |
          echo "Esperando a que MongoDB esté disponible..."
          sleep 10

      - name: Ejecutar pruebas de integración
        run: |
          echo "Ejecutando pruebas de integración..."
          go test ./integration_tests -v

      - name: Apagar contenedores
        if: always()
        run: docker compose down
