name: Build, Scan, Push and Run Container Locally

on:
  push:
    branches: [ "main" ]

jobs:
  build-scan-push-run:
    runs-on: self-hosted  # Tu runner local

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/hlopez:latest .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ secrets.DOCKER_USERNAME }}/hlopez:latest'
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'

    - name: Push image to Docker Hub
      if: success()
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/hlopez:latest

    - name: Run container locally
      if: success()
      run: |
        docker stop hlopez || true
        docker rm hlopez || true
        docker run -d -p 8080:8080 --name hlopez ${{ secrets.DOCKER_USERNAME }}/hlopez:latest
